[python/quart] Fix failing test (#9656)
This fixes the failing quart test because Werkzeug version 3 removed
`url_quote` raising:

    ImportError: cannot import name 'url_quote' from 'werkzeug.urls'