[python/flask] Pin Werkzeug version
This fixes the failing flask test because Werkzeug version 3 removed
`url_quote` raising:

    ImportError: cannot import name 'url_quote' from 'werkzeug.urls'