Rust/rocket: update rocket version to latest
Can't build it anymore with the old version:
```
$ cargo build --release
    Updating crates.io index
error: failed to select a version for the requirement `ring = "^0.11.0"`
  candidate versions found which didn't match: 0.14.0, 0.13.5, 0.8.1
  location searched: crates.io index
required by package `cookie v0.9.1`
    ... which is depended on by `rocket v0.3.15`
    ... which is depended on by `rocket v0.1.0`
```