Rust/rocket: update rocket version to latest (#4344)
* Rust/rocket: update rocket version to latest

Can't build it anymore with the old version:
```
$ cargo build --release
    Updating crates.io index
error: failed to select a version for the requirement `ring = "^0.11.0"`
  candidate versions found which didn't match: 0.14.0, 0.13.5, 0.8.1
  location searched: crates.io index
required by package `cookie v0.9.1`
    ... which is depended on by `rocket v0.3.15`
    ... which is depended on by `rocket v0.1.0`
```

* Rust/rocket/Cargo.toml: don't depend on `rocket_codegen`

Should not be done anymore:
https://github.com/SergioBenitez/Rocket/blob/master/CHANGELOG.md#codegen-rewrite

* Rust/rocket/src/main.rs: update prelude for rocket

As instructed in https://github.com/SergioBenitez/Rocket/blob/master/CHANGELOG.md#codegen-rewrite.

* Rust/rocket/src/main.rs: fix changed imports

Items in `rocket_contrib` were moved under namespaces:
https://github.com/SergioBenitez/Rocket/blob/master/CHANGELOG.md#breaking-changes

* Rust/rocket/src/main.rs: simplify query params

Didn't compile anymore:
```
error[E0277]: the trait bound `QueryString: rocket::request::FromFormValue<'_>` is not satisfied
  --> src/main.rs:59:30
   |
59 | fn queries(conn: db::DbConn, qs: QueryString) -> Json<Vec<models::World>> {
   |                              ^^^^^^^^^^^^^^^ the trait `rocket::request::FromFormValue<'_>` is not implemented for `QueryString`

error[E0277]: the trait bound `QueryString: rocket::request::FromFormValue<'_>` is not satisfied
   --> src/main.rs:103:30
    |
103 | fn updates(conn: db::DbConn, qs: QueryString) -> Json<Vec<models::World>> {
    |                              ^^^^^^^^^^^^^^^ the trait `rocket::request::FromFormValue<'_>` is not implemented for `QueryString`

error: aborting due to 2 previous errors
```
but anyway, a separate struct shouldn't be needed.